### PR TITLE
Added more swifty guard statements

### PR DESCRIPTION
**Pull request by codestergit**

### CODE REVIEW

**Comment by codestergit** [comment]
I think travis not setupped properly.

```
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'

/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by codestergit** [comment]
@vadimeisenbergibm  @rfdickerson  I have addressed changes. Can you please review it.

**Comment by dfirsht** [comment]
We were recently told by the higher ups that we cannot accept anymore PRs until some legal issues are worked out. We'll let you know when those get resolved!

**Comment by codestergit** [comment]
Thanks

**Comment by dfirsht** [comment]
Hey @codestergit we are now set up to accept contributions. However, you'll need to follow the process in [CONTRIBUTING.md](/IBM-Swift/Kitura/blob/master/CONTRIBUTING.md) before we can accept any PRs from you.

**Comment by codestergit** [comment]
@dfirsht 
Updated the pull request to resolve conflicts. 
Also sent the CLA.

**Comment by dfirsht** [comment]
Hey @codestergit, I'm not sure why Travis is failing, seems to be some internal error. In any case, I manually reviewed the code revisions and they all look good. I'm going to go ahead and merge this in.

**Pull request merged**
