### PR TITLE
swiftlint autocorrect

### PR DESCRIPTION
**Pull request by rob-deans**
## Description
Swiftlint's autocorrect feature mainly reformatting the code 

## Checklist:

- [ ] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by rob-deans** [comment]
@shmuelk @ianpartridge @vadimeisenbergibm this is what happens when you run autocorrect with all the auto correctable rules enabled

**Comment by ianpartridge** [comment]
It all looks sensible, I support this PR. It doesn't catch two spaces in `if  let` - we should open a bug against SwiftLint for that?

**Comment by ianpartridge** [comment]
Also, let's look at https://houndci.com/ for automating this stuff?

**Comment by shmuelk** [comment]
I disagree. I don't like what it does with if else.

Here is an example:

-        }
-        else if name.hasPrefix("HTTP_") {
-            
+
+        } else if name.hasPrefix("HTTP_") { 

It is placing the else on the same line as the closing brace of the if.

**Comment by vadimeisenbergibm** [comment]
What is wrong with that? Note that in the original code above other `else if` statements are on the line of the closing brace. These are our Code Conventions, see https://github.com/raywenderlich/swift-style-guide#spacing, https://github.com/apple/swift-package-manager/blob/1bfda9bbdb963e11c8144c89b6b260106d38be6d/Sources/Utility/PkgConfig.swift#L139 .

**Pull request closed without merging**
