### PR TITLE
Improved performance of Date -> HTTP Date String conversion, added ex…

### PR DESCRIPTION
**Pull request by ogres**
Improved performance of Date -> HTTP Date String conversion.

Currently on my machine, for 100000 iterations

**old httpDate(_ date: Date) -> String** takes 6.39880204200745 seconds,
**new httpDate(_ date: Date) -> String** takes 0.104449987411499 seconds

Also added extension to Date type, 
It would be easier to use calculated property on Date instead of directly accessing SPIUtils ( especially for newbies )

### CODE REVIEW

**Comment by ianpartridge** [comment]
Thank you for your PR! This looks good.

Can you complete and email a CLA?  https://github.com/IBM-Swift/CLA

Thank you.

**Comment by ogres** [comment]
Done.

**Comment by djones6** [comment]
There are two places where we use `SPIUtils.httpDate(date: Date)` as opposed to `httpDate()` internally:  setting the last-modified header when serving a static file, and setting a cookie expiry date.  Both cases should benefit significantly from this improvement.

Benchmark results for this PR with some simple testcases ([DatePerf/main.swift](https://github.com/djones6/Swift-TechEmpower/blob/master/kitura/Sources/DatePerf/main.swift)):

Static file serving - returning a small text file:
```
Implementation | Avg Throughput | Max Throughput | Avg CPU | Avg RSS (kb) | Avg Lat (ms) | Max Lat (ms)
---------------|----------------|----------------|---------|--------------|--------------|--------------
Linux:
      baseline |        11898.2 |       12137.74 |    92.2 |        70144 |         18.1 |       283.93
        PR 121 |        18196.6 |       18409.77 |    88.2 |        70062 |         13.5 |       245.64
Mac:
      baseline |         7809.0 |        7837.49 |    56.8 |              |         16.3 |        96.81
        PR 121 |        15491.3 |       15606.35 |    93.5 |              |          8.7 |         90.1
```
Returning httpDate(Date) as plaintext:
```
Implementation | Avg Throughput | Max Throughput | Avg CPU | Avg RSS (kb) | Avg Lat (ms) | Max Lat (ms)
---------------|----------------|----------------|---------|--------------|--------------|--------------
Linux:
      baseline |        23219.3 |       23304.16 |    99.2 |        27372 |          6.0 |        80.46
        PR 121 |        52462.3 |       52975.59 |    90.1 |        26418 |          2.7 |       202.04
Mac:
      baseline |         9941.8 |        9979.98 |    42.0 |              |         12.8 |        21.72
        PR 121 |        43056.4 |       43622.98 |    95.8 |              |          2.9 |        23.75
```
Returning httpDate() as plaintext:
```
Implementation | Avg Throughput | Max Throughput | Avg CPU | Avg RSS (kb) | Avg Lat (ms) | Max Lat (ms)
---------------|----------------|----------------|---------|--------------|--------------|--------------
Linux:
      baseline |        49851.4 |       50138.55 |    91.3 |        27109 |          2.9 |       213.27
        PR 121 |        49678.8 |       49986.75 |    90.8 |        27200 |          2.9 |       204.97
Mac:
      baseline |        42815.9 |       42897.40 |    94.7 |              |          2.9 |        21.75
        PR 121 |        43006.7 |       43034.95 |    95.7 |              |          2.9 |        23.97
```

**Comment by shmuelk** [comment]
Merging. It needs some documentation tweaks, I'll do that later.

**Pull request merged**
