### PR TITLE
Update to use BlueSocket 0.3.x

### PR DESCRIPTION
**Pull request by akrabat**
Update to use BlueSocket 0.3.x rather than 0.2.

I also fixed all the issues related to using the Swift `March 24, 2016` snapshot.

One thing I'm not sure about is that I [changed](https://github.com/IBM-Swift/Kitura-net/commit/d81120d5511d1a6ba14854d76480ad08a629b0e2):

```swift
let clientSocket = try socket.acceptConnectionAndKeepListening()
```
to 
```swift
let clientSocket = socket
try clientSocket.acceptConnection()
```

But I'm not 100% sure that they are functionally the same...

### CODE REVIEW

**Comment by kweinmeister** [comment]
Thanks for your contribution! So that we can consider your PR, can you please fill out the [CLA form](https://github.com/IBM-Swift/CLA)?

**Comment by akrabat** [comment]
@kweinmeister Sent.

**Comment by billabt** [comment]
The old `acceptConnectionAndKeepListening()` should be `acceptClientConnection()`.  No other changes should be necessary.  The `acceptConnection()` replaces the listener socket.  The `acceptClientConnection()` returns a brand new `Socket` instance and leaves the listener socket alone.

**Comment by akrabat** [comment]
Thanks - I'll update.

**Comment by kweinmeister** [comment]
CLA received!

**Comment by akrabat** [comment]
Updated. (Rebased to remove incorrect change.)

**Comment by akrabat** [comment]
I have no idea what Travis is upset by though...

**Comment by rfdickerson** [comment]
Thanks for the PR @akrabat ! Right now our continuous integration build assumes using Swift 03-01 SNAPSHOT. We are working on ways for perhaps making the toolchain version be more parametrizable.

**Comment by akrabat** [comment]
Aha! I can see why it would be unhappy with this PR then :)

**Comment by tfrank64** [comment]
@akrabat So there are still more changes to be done to get Kitura-net working on the 3/24 Swift snapshot. In order to use your changes, could you re-submit your pull request against the `3_24_migration` branch ASAP. That way, `develop` remains unchanged and we can finish up the necessary migration changes on `3_24_migration`.

**Comment by akrabat** [comment]
@tfrank64 done.

**Pull request closed without merging**
