### PR TITLE
Set SO_NOSIGPIPE on listening sockets to avoid dying from SIGPIPE on interrupted connections.

### PR DESCRIPTION
**Pull request by neotron**
Not sure if this is the best way to put it, but since the FD isn't exposed to the outer layer, it seemed like an appropriate location.

### CODE REVIEW

**Comment by billabt** [comment]
This is going to be in the next version of BlueSocket.

**Comment by neotron** [comment]
Makes sense to keep out platform specific stuff from this layer.

**Comment by kweinmeister** [comment]
Thanks for your PR! Please fill out the one time CLA form at https://github.com/IBM-Swift/CLA so we can accept it. Much appreciated.

**Comment by billabt** [comment]
FYI, there's no `SO_NOSIGPIPE` on Linux.  To avoid the interruption, you need to add a `MSG_NOSIGNAL` flag to the underlying socket send() function.

**Comment by neotron** [comment]
Yeah, I should have known that - have a C++ cross-platform piece of code that uses MSG_NOSIGNAL when available. I assume that this particular change should be closed for now, given that it'll happen in BlueSocket instead of here (and need x-platform change as well).

**Comment by billabt** [comment]
Yup.  Thanks again for your efforts.  Much appreciated.

**Pull request closed without merging**
