### PR TITLE
Improvement of Server lifecycle listener

### PR DESCRIPTION
**Pull request by naithar**
Implemented a perform of callbacks added to `.started` and `.stopped` listener if server has already started or stopped listening.
Implemented a `state` property for Server that represents current server state.
Removed private `stopped` propery

## Motivation and Context
IBM-Swift/Kitura#666

## How Has This Been Tested?
Added test to `LifecycleListenerTests.swift`

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by naithar** [comment]
Seems like linux travis build didn't run properly if i'm understanding the log right

**Comment by shmuelk** [comment]
It looks very good. Please add API documentation for the new APIs. Also please document the APIs you added in your previous PR.

**Comment by naithar** [comment]
@shmuelk done

**Comment by shmuelk** [comment]
Thanks. It really looks great now. We'll merge once the builds run.

**Comment by naithar** [comment]
Seems like travis still didn't run linux correctly

**Comment by naithar** [comment]
Same build but on another branch runs correctly: (branch issue-666-2)[https://travis-ci.org/naithar/Kitura-net/builds/171002776]

**Comment by shmuelk** [comment]
I am looking into these build failures, I can recreate the problem locally.

**Comment by shmuelk** [comment]
The build issues seem to be fixed. Merging.

**Pull request merged**
