### PR TITLE
Refactor Kitura-Net Classes to Reference HTTP (Prep for Multi Protocol)

### PR DESCRIPTION
**Pull request by simplepanda**
As the title describes, this is a refactoring / renaming of: 
- The HTTPServerDelegate class protocol in Kitura-net to simply ServerDelegate. 
- The IncomingMessage class to HTTPIncomingMessage
- ServerRequest and ServerResponse into HTTPServerRequest and HTTPServerResponse

There is also a PR against Kitura to support renaming HTTPServerDelegate

All of this is in relation to IBM-Swift/Kitura#565 

## Description
- Pulled HTTPServerDelegate from the HTTPServer class.
- Placed it in it's own file, ServerDelegate.swift in Kitura-net.
- Replaced all uses of HTTPServerDelegate with ServerDelegate system wide. This affects both the Kitura-Net and Kitura projects.
- Renamed IncomingMessage to HTTPIncomingMessage and updated ClientRequest and ServerRequest accordingly.
- Renamed ServerResponse to HTTPServerResponse
- Renamed ServerRequest to HTTPServerRequest
- Created ServerResponse and ServerRequest class protocols so that other modules (Kitura's Router, specifically) can handle response and requests without understanding the underlying protocol (in preperation for FastCGI addition, which will also use the ServerRequest and ServerResponse protocols)
- Modified HTTPServer to directly use HTTPServerResponse and HTTPServerRequest

## Motivation and Context
ServerDelegate will ultimately be used to provide server protocols other than HTTP and will be used by a forthcoming pull request related to adding a FastCGI server implementation to Kitura. For clarity, this refactor makes it obvious that the ServerDelegate handles more than HTTP and moves it out of the HTTPServer class in the process.

Likewise, IncomingMessage is related exclusively to HTTP operation. Refactoring it to HTTPIncomingMessage makes this clear.

Likewise, ServerRequest and ServerResponse were previously exclusive to HTTP operation. By refactoring them to HTTP-prefixed classes and leaving class protocols in their places, it's now clear that they are related to the HTTP server and other protocols (FastCGI specifically) can inject themselves using the same request and response system.

## How Has This Been Tested?
Change is relatively trivial in terms of a refactor. Did a full rebuild of current test projects I'm working on and everything builds and runs as always. There is no real code changes here - just renames/refactors  for the most part. The class protocols mirror the public functions in the original classes so these will sit in for the classes in all calling code without issue (unless something breaks in Swift proper).

## Checklist:

- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [ ] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by simplepanda** [comment]
At this point, I'm done pushing to this PR; this refactors Kitura-net to make it ready for FastCGI to be added. The next PR would be adding the actual FastCGI code.

If there is anything you'd need to get this PR merged, let me know and I can get it done asap.

Thanks!

**Comment by shmuelk** [comment]
@simplepanda This fundamentally looks ok. But please update the tests. There is now a test in Kitura-net that uses HTTPServerDelegate

**Comment by simplepanda** [comment]
Hi @shmuelk  - I'm just merging back from IBM-Swift/Kitura-net and will push up a commit to update the new tests momentarily.

**Comment by simplepanda** [comment]
Ok @shmuelk  - tests updated and it now passes tests on Linux and Mac after refactoring the new parts of the test suite.

**Comment by simplepanda** [comment]
Note: Modified the PR description to indicate that I updated the tests.

**Comment by shmuelk** [comment]
@simplepanda Thanks. I'll merge this on Sunday. This affects tests in a bunch of other repositories as well. I'll take care of them.

**Comment by simplepanda** [comment]
Thanks @shmuelk! - The next changes I have are all clean adds in that they are either new classes to -Net or straight changes to Kitura.git that don't have major dependency problems. Will be much easier to manage.

**Pull request merged**
